version: '3'

services:
  postgres:
    image: "postgres:15.4"
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myclothing
    volumes:
      - ./.volumes/postgres/data/:/var/lib/postgresql/data/
