// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"database/sql"
)

type AppUser struct {
	AppUserID    int32
	Username     string
	Email        string
	PasswordHash string
	CreatedAt    sql.NullTime
}

type Project struct {
	ProjectID   int32
	ProjectName string
	Description sql.NullString
	CreatedAt   sql.NullTime
	AppUserID   sql.NullInt32
}
